DO NOT MERGE THIS PR YET
PSU-MCECS-SAFE/SAFE pull request #18
Opened 2023-05-04 02:06 UTC by Vincentmask

1. Removed the first three import since we can pass in the client on the server directly.
2. Changing var to let  & const to provide block scoping for variables.
3. In the function that require to connect to the db, added client to the params, so we don't need to connect to db everytime.
4. The sortChars function returns a comma-separated string instead of an array. Therefore, when the concat method is called on the arr variable, it does not modify the array but instead returns a new array with the concatenated value. The concat and return arr.sort().toString() in function 'sortChars' is returning a list of 'undefine' So I changed it to using push, and return arr.sort().join('');
5. Modified queries to using values to prevent malicious actions.
6. use += to replace concat since the .concat() method is used to concatenate arrays or strings, and it returns a new concatenated array or string.

2023-05-04 03:55 UTC, imOnVacation requested changes
Vincent, can you please merge the updated dev branch into this branch and see if everything working as expected? Thanks!

2023-05-04 17:53 UTC, imOnVacation approved these changes, later dismissed

2023-05-05 05:33 UTC, McJefe approved these changes
The checkProfanities function killed me lol. We should update it at some point, but this all looks good.

2023-05-05 14:34 UTC, rsanch2 approved these changes

2023-05-06 00:08 UTC, NAlexH2 approved these changes

2023-05-08 06:12 UTC, imOnVacation commented
Please don't touch this PR before meeting with Mark.

2023-05-09 03:51 UTC, merged